// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutlookSync.Infrastructure.Persistence;

#nullable disable

namespace OutlookSync.Infrastructure.Migrations
{
    [DbContext(typeof(OutlookSyncDbContext))]
    [Migration("20260211135538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItemsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Calendars", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenAcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.SyncConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId")
                        .IsUnique();

                    b.ToTable("SyncConfigs", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Device", b =>
                {
                    b.OwnsOne("OutlookSync.Domain.ValueObjects.DeviceInfo", "Info", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Info")
                        .IsRequired();
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.SyncConfig", b =>
                {
                    b.OwnsOne("OutlookSync.Domain.ValueObjects.SyncConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("SyncConfigId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsPrivate")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("SyncConfigId");

                            b1.ToTable("SyncConfigs");

                            b1.WithOwner()
                                .HasForeignKey("SyncConfigId");

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.CalendarFieldSelection", "FieldSelection", b2 =>
                                {
                                    b2.Property<Guid>("SyncConfigurationSyncConfigId")
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("Attendees")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Body")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("EndTime")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsAllDay")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Location")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Organizer")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Recurrence")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("StartTime")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Subject")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("SyncConfigurationSyncConfigId");

                                    b2.ToTable("SyncConfigs");

                                    b2.WithOwner()
                                        .HasForeignKey("SyncConfigurationSyncConfigId");
                                });

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.SyncInterval", "Interval", b2 =>
                                {
                                    b2.Property<Guid>("SyncConfigurationSyncConfigId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CronExpression")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Minutes")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("SyncConfigurationSyncConfigId");

                                    b2.ToTable("SyncConfigs");

                                    b2.WithOwner()
                                        .HasForeignKey("SyncConfigurationSyncConfigId");
                                });

                            b1.Navigation("FieldSelection")
                                .IsRequired();

                            b1.Navigation("Interval")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
