// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutlookSync.Infrastructure.Persistence;

#nullable disable

namespace OutlookSync.Infrastructure.Migrations
{
    [DbContext(typeof(OutlookSyncDbContext))]
    [Migration("20260218101131_RemoveCalendarTable")]
    partial class RemoveCalendarTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.CalendarBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSyncEventCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCalendarExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceCredentialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCalendarExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetCredentialId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceCredentialId", "SourceCalendarExternalId", "TargetCredentialId", "TargetCalendarExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_CalendarBindings_SourceTarget_Unique");

                    b.ToTable("CalendarBindings", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("StatusData")
                        .HasColumnType("BLOB")
                        .HasColumnName("StatusData");

                    b.Property<int>("TokenStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.CalendarBinding", b =>
                {
                    b.OwnsOne("OutlookSync.Domain.ValueObjects.CalendarBindingConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("CalendarBindingId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CopyAttachments")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CopyConferenceLink")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CopyDescription")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CopyLocation")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CopyParticipants")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CustomTag")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CustomTagInTitle")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CustomTitle")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<bool>("MarkAsPrivate")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ReminderHandling")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TargetCategory")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TargetEventColor")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TargetStatus")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TitleHandling")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("CalendarBindingId");

                            b1.ToTable("CalendarBindings");

                            b1.WithOwner()
                                .HasForeignKey("CalendarBindingId");

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.ColorExclusionRule", "ColorExclusion", b2 =>
                                {
                                    b2.Property<Guid>("CalendarBindingConfigurationCalendarBindingId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ExcludedColors")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ExcludedColors");

                                    b2.HasKey("CalendarBindingConfigurationCalendarBindingId");

                                    b2.ToTable("CalendarBindings");

                                    b2.WithOwner()
                                        .HasForeignKey("CalendarBindingConfigurationCalendarBindingId");
                                });

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.RsvpExclusionRule", "RsvpExclusion", b2 =>
                                {
                                    b2.Property<Guid>("CalendarBindingConfigurationCalendarBindingId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ExcludedResponses")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ExcludedRsvpResponses");

                                    b2.HasKey("CalendarBindingConfigurationCalendarBindingId");

                                    b2.ToTable("CalendarBindings");

                                    b2.WithOwner()
                                        .HasForeignKey("CalendarBindingConfigurationCalendarBindingId");
                                });

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.StatusExclusionRule", "StatusExclusion", b2 =>
                                {
                                    b2.Property<Guid>("CalendarBindingConfigurationCalendarBindingId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ExcludedStatuses")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ExcludedStatuses");

                                    b2.HasKey("CalendarBindingConfigurationCalendarBindingId");

                                    b2.ToTable("CalendarBindings");

                                    b2.WithOwner()
                                        .HasForeignKey("CalendarBindingConfigurationCalendarBindingId");
                                });

                            b1.Navigation("ColorExclusion")
                                .IsRequired();

                            b1.Navigation("RsvpExclusion")
                                .IsRequired();

                            b1.Navigation("StatusExclusion")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
