// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutlookSync.Infrastructure.Persistence;

#nullable disable

namespace OutlookSync.Infrastructure.Migrations
{
    [DbContext(typeof(OutlookSyncDbContext))]
    partial class OutlookSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Calendars", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("StatusData")
                        .HasColumnType("BLOB")
                        .HasColumnName("StatusData");

                    b.Property<int>("TokenStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("OutlookSync.Domain.Aggregates.Calendar", b =>
                {
                    b.OwnsOne("OutlookSync.Domain.ValueObjects.SyncConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("CalendarId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsPrivate")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("TEXT");

                            b1.Property<int>("SyncDaysForward")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(30);

                            b1.HasKey("CalendarId");

                            b1.ToTable("Calendars");

                            b1.WithOwner()
                                .HasForeignKey("CalendarId");

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.CalendarFieldSelection", "FieldSelection", b2 =>
                                {
                                    b2.Property<Guid>("SyncConfigurationCalendarId")
                                        .HasColumnType("TEXT");

                                    b2.Property<bool>("Attendees")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Body")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("EndTime")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsAllDay")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Location")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Organizer")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Recurrence")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("StartTime")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("Subject")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("SyncConfigurationCalendarId");

                                    b2.ToTable("Calendars");

                                    b2.WithOwner()
                                        .HasForeignKey("SyncConfigurationCalendarId");
                                });

                            b1.OwnsOne("OutlookSync.Domain.ValueObjects.SyncInterval", "Interval", b2 =>
                                {
                                    b2.Property<Guid>("SyncConfigurationCalendarId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CronExpression")
                                        .HasMaxLength(50)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Minutes")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("SyncConfigurationCalendarId");

                                    b2.ToTable("Calendars");

                                    b2.WithOwner()
                                        .HasForeignKey("SyncConfigurationCalendarId");
                                });

                            b1.Navigation("FieldSelection")
                                .IsRequired();

                            b1.Navigation("Interval")
                                .IsRequired();
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
